### ISSUE TITLE
Cut New Release

### ISSUE THREAD

**Issue by osterman** [wrouesnel/emailcli#1]
## what
* Cut a new release

## why
* Latest code was merged ~1 year ago
* Latest release is from 2016

**Comment by wrouesnel** [comment]
Let's make that happen! https://github.com/wrouesnel/emailcli/releases/tag/v0.0.2 (should be built shortly)

**Comment by osterman** [comment]
@wrouesnel I think due to the recent GitHub outage the build did not get triggered. They disabled webhooks for a period of time.

**Comment by osterman** [comment]
(Thanks for the prompt response!)

We're using your 12-factor compatible cli tool with our new terraform module for sending transactional emails related to `terraform apply`

https://github.com/cloudposse/terraform-null-smtp-mail/pull/1

**Comment by osterman** [comment]
And we'll be distributing it as part of our toolchain in our Alpine repo: https://github.com/cloudposse/packages/pull/95

**Comment by osterman** [comment]
@wrouesnel there's still no binary attachment on the release. Can you take a look? =)

**Comment by wrouesnel** [comment]
Finally building (caught the tail end of the github outage and then you know, had to sleep :)

**Comment by osterman** [comment]
lol, yea, that was a pretty bad 24 hour outage! I was working the minute it hit. Thanks for getting that taken care of! we'll release that.
